name = "PlanarConvexHulls"
uuid = "145d500b-351c-58b3-a0aa-f5d7e249d989"
authors = ["Twan Koolen <koolen.twan@gmail.com>"]
version = "0.3.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DocStringExtensions = "^0.8"
StaticArrays = "^1.5"
julia = "1.6"

